server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: resource-service-one
          uri: lb://resource-service-one
          predicates:
            - Path=/resource/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: resource-service-one-websocket
          uri: lb:ws://resource-service-one
          predicates:
            - Path=/chat
          filters:
            - RemoveRequestHeader=Cookie
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

ribbon:
  eager-load:
    enabled: true